### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by craigaaroncampbell** [timcmiller/framework_app#1]
possible aspects of
the project

**Comment by craigaaroncampbell** [comment]
automate content-type, etc..   - extname from Node's built-in path module?

default parameters such as port  (e.g. argv[] || somevar || 3000)?

automate routes?

ruby-on-rails-like auto-setup?

parse url - Kenji, what were you thinking about this? I wasn't clear.

**Comment by KenjiCrosland** [comment]
The parse URL takes the url string and splits it by ["/"]. We could use it in our routing.
